services:
  - type: web
    name: ema200signal-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    region: singapore
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
